# Root URL where files are stored/hosted
root_url: https://public.wiwdata.com/engineering-challenge/data/
# directory to download files to
download_directory: temp\\

# transformation settings
tf:
  columns:
  - user_id
  - length
  - path
  index: user_id
